<?php

/**
 * Created by PhpStorm.
 * User: Lukas
 * Date: 09.05.2016
 * Time: 21:50
 */

namespace xxx\Controllers {

    use xxx\Renderers\FrontPageRenderer;
    
    class FrontPageController extends AbstractController
    {
        /**
         * @var 
         * 
         */
        private $pageContent;

        /**
         * @var
         *
         */
        private $template;

        /**
         * @var FrontPageRenderer
         *
         */
        private $pageRenderer;
        
        public function run()
        {
            $this->pageContent = $this->loadDom('/var/www/StartNewProject/data/Pages/FrontPageContent.html');
            $this->template = $this->loadTemplate();
            $this->pageRenderer = new FrontPageRenderer();

            return parent::run(); // TODO: Change the autogenerated stub
        }

        //Lässt den Body rendern und gibt ihn dann aus.
        protected function getBody()
        {
            return $this->pageRenderer->renderFrontpage($this->template, $this->pageContent);
        }
    }
}