xxx<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'xxx\\controllers\\abstractcontroller' => '/Controllers/AbstractController.php',
                'xxx\\controllers\\frontpagecontroller' => '/Controllers/FrontPageController.php',
                'xxx\\controllers\\logincontroller' => '/Controllers/LoginController.php',
                'xxx\\controllers\\loginformpagecontroller' => '/Controllers/LoginFormPageController.php',
                'xxx\\controllers\\profilepagecontroller' => '/Controllers/ProfilePageController.php',
                'xxx\\controllers\\registerformpagecontroller' => '/Controllers/RegisterFormPageController.php',
                'xxx\\controllers\\registercontroller' => '/Controllers/RegisterController.php',
                'xxx\\handlers\\loginhandler' => '/Handlers/LoginHandler.php',
                'xxx\\handlers\\registerhandler' => '/Handlers/RegisterHandler.php',
                'xxx\\loaders\\loader' => '/Loaders/Loader.php',
                'xxx\\queries\\registerquery' => '/Queries/RegisterQuery.php',
                'xxx\\queries\\selectuserfromdatabasequery' => '/Queries/SelectUserFromDatabaseQuery.php',
                'xxx\\responses\\response' => '/Responses/Response.php',
                'xxx\\renderers\\frontpagerenderer' => '/Renderers/FrontPageRenderer.php',
                'xxx\\renderers\\loginformpagerenderer' => '/Renderers/LoginFormPageRenderer.php',
                'xxx\\renderers\\profilepagerenderer' => '/Renderers/ProfilePageRenderer.php',
                'xxx\\renderers\\registerformpagerenderer' => '/Renderers/RegisterFormPageRenderer.php',
                'xxx\\routers\\router' => '/Routers/Router.php',
                'xxx\\valueobjects\\hashpassword' => '/ValueObjects/HashPassword.php',
                'xxx\\valueobjects\\userfromdatabase' => '/ValueObjects/UserFromDatabase.php',
                'xxx\\wrappers\\databasewrapper' => '/Wrappers/DatabaseWrapper.php',
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
