<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'xxx\\controllers\\abstractcontroller' => '/Controllers/AbstractController.php',
                'xxx\\controllers\\frontpagecontroller' => '/Controllers/FrontPageController.php',
                'xxx\\loaders\\loader' => '/Loaders/Loader.php',
                'xxx\\responses\\response' => '/Responses/Response.php',
                'xxx\\renderers\\frontpagerenderer' => '/Renderers/FrontPageRenderer.php',
                'xxx\\routers\\router' => '/Routers/Router.php',
                'xxx\\wrappers\\databasewrapper' => '/Wrappers/DatabaseWrapper.php',
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
